curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/01_prep.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/02_partition.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/03_mount.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/04_pacstrap.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/05_base.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/06_software_core.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/07_software_extra.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/08_kde.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/08_kde_minimal.sh
curl -LO https://raw.githubusercontent.com/JamesMowery/arch/main/installation/08_ghome.sh
