echo "Create directories: mkdir -p /mnt/boot/efi"
echo "Run: mount /dev/</> /mnt"
echo "Run mount /dev/</home> /mnt/home"
echo "Run: mount/dev/</boot> /mnt/boot/efi"
echo "Run: swapon /dev/<swap>"
echo "---------------------------------------"
echo "Continue with 04_pacstrap.sh"
